# This file has been autogenerated by the pywayland scanner

# Copyright © 2018 Ilia Bozhinov
# Copyright © 2020 Isaac Freund
# Copyright © 2022 wb9688
# Copyright © 2024 Victoria Brekenfeld
#
# Permission to use, copy, modify, distribute, and sell this
# software and its documentation for any purpose is hereby granted
# without fee, provided that the above copyright notice appear in
# all copies and that both that copyright notice and this permission
# notice appear in supporting documentation, and that the name of
# the copyright holders not be used in advertising or publicity
# pertaining to distribution of the software without specific,
# written prior permission.  The copyright holders make no
# representations about the suitability of this software for any
# purpose.  It is provided "as is" without express or implied
# warranty.
#
# THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
# SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
# SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
# AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
# ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
# THIS SOFTWARE.

from __future__ import annotations

import enum

from pywayland.protocol_core import Argument, ArgumentType, Global, Interface, Proxy, Resource

from .cosmic_toplevel_info_unstable_v1 import ZcosmicToplevelHandleV1
from .cosmic_toplevel_info_unstable_v1 import ZcosmicToplevelHandleV1Proxy
from .ext_workspace_v1_stub import ExtWorkspaceHandleV1
from .ext_workspace_v1_stub import ExtWorkspaceHandleV1Proxy
from .ext_workspace_v1_stub import ZcosmicWorkspaceHandleV1
from .ext_workspace_v1_stub import ZcosmicWorkspaceHandleV1Proxy
from pywayland.protocol.wayland import WlOutput
from pywayland.protocol.wayland import WlOutputProxy
from pywayland.protocol.wayland import WlSeat
from pywayland.protocol.wayland import WlSeatProxy
from pywayland.protocol.wayland import WlSurface
from pywayland.protocol.wayland import WlSurfaceProxy


class ZcosmicToplevelManagerV1(Interface):
    """Control open apps

    This protocol allows clients such as a taskbar to request the compositor to
    preform typical actions on open toplevels. The compositor is in all cases
    free to ignore the request.
    """

    name = "zcosmic_toplevel_manager_v1"
    version = 4

    class zcosmic_toplelevel_management_capabilities_v1(enum.IntEnum):
        close = 1
        activate = 2
        maximize = 3
        minimize = 4
        fullscreen = 5
        move_to_workspace = 6
        sticky = 7
        move_to_ext_workspace = 8

    class error(enum.IntEnum):
        invalid_rectangle = 0


class ZcosmicToplevelManagerV1Resource(Resource[ZcosmicToplevelManagerV1]):
    interface = ZcosmicToplevelManagerV1

    @ZcosmicToplevelManagerV1.event(
        Argument(ArgumentType.Array),
    )
    def capabilities(self, capabilities: list) -> None:
        """Compositor capabilities

        This event advertises the capabilities supported by the compositor. If
        a capability isn't supported, clients should hide or disable the UI
        elements that expose this functionality. For instance, if the
        compositor doesn't advertise support for closing toplevels, a button
        triggering the close request should not be displayed.

        The compositor will ignore requests it doesn't support. For instance, a
        compositor which doesn't advertise support for closing toplevels will
        ignore close requests.

        Compositors must send this event once after creation of an
        :class:`ZcosmicToplevelManagerV1` . When the capabilities change,
        compositors must send this event again.

        The capabilities are sent as an array of 32-bit unsigned integers in
        native endianness.

        :param capabilities:
            array of 32-bit capabilities
        :type capabilities:
            `ArgumentType.Array`
        """
        self._post_event(0, capabilities)


class ZcosmicToplevelManagerV1Proxy(Proxy[ZcosmicToplevelManagerV1]):
    interface = ZcosmicToplevelManagerV1

    @ZcosmicToplevelManagerV1.request()
    def destroy(self) -> None:
        """Destroy the :class:`ZcosmicToplevelManagerV1`

        This request indicates that the client has finished using the
        :class:`ZcosmicToplevelManagerV1` object and that it can be safely
        destroyed.
        """
        self._marshal(0)
        self._destroy()

    @ZcosmicToplevelManagerV1.request(
        Argument(ArgumentType.Object, interface=ZcosmicToplevelHandleV1),
    )
    def close(self, toplevel: ZcosmicToplevelHandleV1Proxy) -> None:
        """Request that a toplevel be closed

        If the compositor honors this request, the
        :func:`ZcosmicToplevelHandleV1.closed()
        <pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1.closed>`
        event will be sent.

        :param toplevel:
        :type toplevel:
            :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        """
        self._marshal(1, toplevel)

    @ZcosmicToplevelManagerV1.request(
        Argument(ArgumentType.Object, interface=ZcosmicToplevelHandleV1),
        Argument(ArgumentType.Object, interface=WlSeat),
    )
    def activate(self, toplevel: ZcosmicToplevelHandleV1Proxy, seat: WlSeatProxy) -> None:
        """Request that a toplevel be activated

        If the compositor honors this request, the
        :func:`ZcosmicToplevelHandleV1.state()
        <pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1.state>`
        event will be sent.

        :param toplevel:
        :type toplevel:
            :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        :param seat:
        :type seat:
            :class:`~pywayland.protocol.wayland.WlSeat`
        """
        self._marshal(2, toplevel, seat)

    @ZcosmicToplevelManagerV1.request(
        Argument(ArgumentType.Object, interface=ZcosmicToplevelHandleV1),
    )
    def set_maximized(self, toplevel: ZcosmicToplevelHandleV1Proxy) -> None:
        """Request that a toplevel be maximized

        If the compositor honors this request, the
        :func:`ZcosmicToplevelHandleV1.state()
        <pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1.state>`
        event will be sent.

        :param toplevel:
        :type toplevel:
            :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        """
        self._marshal(3, toplevel)

    @ZcosmicToplevelManagerV1.request(
        Argument(ArgumentType.Object, interface=ZcosmicToplevelHandleV1),
    )
    def unset_maximized(self, toplevel: ZcosmicToplevelHandleV1Proxy) -> None:
        """Request that a toplevel be unmaximized

        If the compositor honors this request, the
        :func:`ZcosmicToplevelHandleV1.state()
        <pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1.state>`
        event will be sent.

        :param toplevel:
        :type toplevel:
            :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        """
        self._marshal(4, toplevel)

    @ZcosmicToplevelManagerV1.request(
        Argument(ArgumentType.Object, interface=ZcosmicToplevelHandleV1),
    )
    def set_minimized(self, toplevel: ZcosmicToplevelHandleV1Proxy) -> None:
        """Request that a toplevel be minimized

        If the compositor honors this request, the
        :func:`ZcosmicToplevelHandleV1.state()
        <pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1.state>`
        event will be sent.

        :param toplevel:
        :type toplevel:
            :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        """
        self._marshal(5, toplevel)

    @ZcosmicToplevelManagerV1.request(
        Argument(ArgumentType.Object, interface=ZcosmicToplevelHandleV1),
    )
    def unset_minimized(self, toplevel: ZcosmicToplevelHandleV1Proxy) -> None:
        """Request that a toplevel be unminimized

        If the compositor honors this request, the
        :func:`ZcosmicToplevelHandleV1.state()
        <pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1.state>`
        event will be sent.

        :param toplevel:
        :type toplevel:
            :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        """
        self._marshal(6, toplevel)

    @ZcosmicToplevelManagerV1.request(
        Argument(ArgumentType.Object, interface=ZcosmicToplevelHandleV1),
        Argument(ArgumentType.Object, interface=WlOutput, nullable=True),
    )
    def set_fullscreen(self, toplevel: ZcosmicToplevelHandleV1Proxy, output: WlOutputProxy | None) -> None:
        """Request that a toplevel be fullscreened

        If the compositor honors this request, the
        :func:`ZcosmicToplevelHandleV1.state()
        <pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1.state>`
        and potentially the :func:`ZcosmicToplevelHandleV1.output_enter()
        <pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1.output_enter>`/output_leave
        events will be sent.

        The output parameter a hint to the compositor and may be ignored. A
        value of NULL indicates that the compositor should choose the target
        output, if it honors the fullscreen request.

        :param toplevel:
        :type toplevel:
            :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        :param output:
        :type output:
            :class:`~pywayland.protocol.wayland.WlOutput` or `None`
        """
        self._marshal(7, toplevel, output)

    @ZcosmicToplevelManagerV1.request(
        Argument(ArgumentType.Object, interface=ZcosmicToplevelHandleV1),
    )
    def unset_fullscreen(self, toplevel: ZcosmicToplevelHandleV1Proxy) -> None:
        """Request that a toplevel be unfullscreened

        If the compositor honors this request, the
        :func:`ZcosmicToplevelHandleV1.state()
        <pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1.state>`
        event will be sent.

        :param toplevel:
        :type toplevel:
            :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        """
        self._marshal(8, toplevel)

    @ZcosmicToplevelManagerV1.request(
        Argument(ArgumentType.Object, interface=ZcosmicToplevelHandleV1),
        Argument(ArgumentType.Object, interface=WlSurface),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def set_rectangle(self, toplevel: ZcosmicToplevelHandleV1Proxy, surface: WlSurfaceProxy, x: int, y: int, width: int, height: int) -> None:
        """Designate a rectangle to represent a toplevel

        If a client using this protocol displays UI elements corresponding to
        toplevels, it may use this request to inform the server about such a
        relation. This information may be used by the server, for example as
        the target for a minimize animation.

        If the client sets more than one rectangle, only the most recently set
        rectangle is considered.

        The dimensions are given in surface-local coordinates.

        Setting width=height=0 removes the current rectangle if one was set.

        :param toplevel:
        :type toplevel:
            :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        :param surface:
        :type surface:
            :class:`~pywayland.protocol.wayland.WlSurface`
        :param x:
        :type x:
            `ArgumentType.Int`
        :param y:
        :type y:
            `ArgumentType.Int`
        :param width:
        :type width:
            `ArgumentType.Int`
        :param height:
        :type height:
            `ArgumentType.Int`
        """
        self._marshal(9, toplevel, surface, x, y, width, height)

    @ZcosmicToplevelManagerV1.request(
        Argument(ArgumentType.Object, interface=ZcosmicToplevelHandleV1),
        Argument(ArgumentType.Object, interface=ZcosmicWorkspaceHandleV1),
        Argument(ArgumentType.Object, interface=WlOutput),
        version=2,
    )
    def move_to_workspace(self, toplevel: ZcosmicToplevelHandleV1Proxy, workspace: ZcosmicWorkspaceHandleV1Proxy, output: WlOutputProxy) -> None:
        """Move toplevel to workspace

        Move window to workspace, on given output.

        :param toplevel:
        :type toplevel:
            :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        :param workspace:
        :type workspace:
            :class:`~pywayland.protocol.ext_workspace_v1_stub.ZcosmicWorkspaceHandleV1`
        :param output:
        :type output:
            :class:`~pywayland.protocol.wayland.WlOutput`
        """
        self._marshal(10, toplevel, workspace, output)

    @ZcosmicToplevelManagerV1.request(
        Argument(ArgumentType.Object, interface=ZcosmicToplevelHandleV1),
        version=3,
    )
    def set_sticky(self, toplevel: ZcosmicToplevelHandleV1Proxy) -> None:
        """Request that a toplevel be made sticky

        If the compositor honors this request, the
        :func:`ZcosmicToplevelHandleV1.state()
        <pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1.state>`
        event will be sent.

        :param toplevel:
        :type toplevel:
            :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        """
        self._marshal(11, toplevel)

    @ZcosmicToplevelManagerV1.request(
        Argument(ArgumentType.Object, interface=ZcosmicToplevelHandleV1),
        version=3,
    )
    def unset_sticky(self, toplevel: ZcosmicToplevelHandleV1Proxy) -> None:
        """Request that a toplevel be removed of the sticky status

        If the compositor honors this request, the
        :func:`ZcosmicToplevelHandleV1.state()
        <pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1.state>`
        event will be sent.

        :param toplevel:
        :type toplevel:
            :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        """
        self._marshal(12, toplevel)

    @ZcosmicToplevelManagerV1.request(
        Argument(ArgumentType.Object, interface=ZcosmicToplevelHandleV1),
        Argument(ArgumentType.Object, interface=ExtWorkspaceHandleV1),
        Argument(ArgumentType.Object, interface=WlOutput),
        version=4,
    )
    def move_to_ext_workspace(self, toplevel: ZcosmicToplevelHandleV1Proxy, workspace: ExtWorkspaceHandleV1Proxy, output: WlOutputProxy) -> None:
        """Move toplevel to workspace

        Move window to workspace, on given output.

        :param toplevel:
        :type toplevel:
            :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        :param workspace:
        :type workspace:
            :class:`~pywayland.protocol.ext_workspace_v1_stub.ExtWorkspaceHandleV1`
        :param output:
        :type output:
            :class:`~pywayland.protocol.wayland.WlOutput`
        """
        self._marshal(13, toplevel, workspace, output)


class ZcosmicToplevelManagerV1Global(Global[ZcosmicToplevelManagerV1]):
    interface = ZcosmicToplevelManagerV1


ZcosmicToplevelManagerV1._gen_c()
ZcosmicToplevelManagerV1.proxy_class = ZcosmicToplevelManagerV1Proxy
ZcosmicToplevelManagerV1.resource_class = ZcosmicToplevelManagerV1Resource
ZcosmicToplevelManagerV1.global_class = ZcosmicToplevelManagerV1Global
