# This file has been autogenerated by the pywayland scanner

# Copyright 2015 Sean Vig
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

from pywayland.protocol_core import Global, Interface, Proxy, Resource


class ExtWorkspaceHandleV1(Interface):
    name = "ext_workspace_handle_v1"
    version = 1


class ZcosmicWorkspaceHandleV1(Interface):
    name = "zcosmic_workspace_handle_v1"
    version = 1


class ExtWorkspaceHandleV1Resource(Resource[ExtWorkspaceHandleV1]):
    interface = ExtWorkspaceHandleV1


class ZcosmicWorkspaceHandleV1Resource(Resource[ZcosmicWorkspaceHandleV1]):
    interface = ZcosmicWorkspaceHandleV1


class ExtWorkspaceHandleV1Proxy(Proxy[ExtWorkspaceHandleV1]):
    interface = ExtWorkspaceHandleV1

    @ExtWorkspaceHandleV1.request()
    def destroy(self) -> None:
        """destroy
        """
        self._marshal(0)
        self._destroy()


class ZcosmicWorkspaceHandleV1Proxy(Proxy[ZcosmicWorkspaceHandleV1]):
    interface = ZcosmicWorkspaceHandleV1

    @ZcosmicWorkspaceHandleV1.request()
    def destroy(self) -> None:
        """destroy
        """
        self._marshal(0)
        self._destroy()


class ExtWorkspaceHandleV1Global(Global[ExtWorkspaceHandleV1]):
    interface = ExtWorkspaceHandleV1


class ZcosmicWorkspaceHandleV1Global(Global[ZcosmicWorkspaceHandleV1]):
    interface = ZcosmicWorkspaceHandleV1


ExtWorkspaceHandleV1._gen_c()
ExtWorkspaceHandleV1.proxy_class = ExtWorkspaceHandleV1Proxy
ExtWorkspaceHandleV1.resource_class = ExtWorkspaceHandleV1Resource
ExtWorkspaceHandleV1.global_class = ExtWorkspaceHandleV1Global


ZcosmicWorkspaceHandleV1._gen_c()
ZcosmicWorkspaceHandleV1.proxy_class = ZcosmicWorkspaceHandleV1Proxy
ZcosmicWorkspaceHandleV1.resource_class = ZcosmicWorkspaceHandleV1Resource
ZcosmicWorkspaceHandleV1.global_class = ZcosmicWorkspaceHandleV1Global
